dist: trusty
sudo: true
language: python
python:
    - "3.6"
services:
    - mysql
env:
    - RUNNING_TRAVIS=true
install:
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv install --system --skip-lock
before_script:
    - sudo cat "$TRAVIS_BUILD_DIR/RubikVNdotOrg/db/my.cnf" > /etc/mysql/my.cnf
    - sudo service mysql restart
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test_rubikvn;'
    - mysql -u root --default-character-set=utf8mb4 test_rubikvn < $TRAVIS_BUILD_DIR/RubikVNdotOrg/db/rubikvn_schema.sql
script:
    pipenv run python manage.py test --keepdb
notifications:
    email: false
